FROM node:20-alpine AS base

WORKDIR /app
ENV NEXT_TELEMETRY_DISABLED=1

ARG NEXT_PUBLIC_NAME
ARG NEXT_PUBLIC_DESCRIPTION
ARG NEXT_PUBLIC_LOGO_PATH
ARG NEXT_PUBLIC_NEXTAUTH_URL
ARG NEXT_PUBLIC_API_RENIEC_DNI
ARG NEXT_PUBLIC_API_RENIEC_RUC
ARG DATABASE_URL

ENV NEXT_PUBLIC_NAME=${NEXT_PUBLIC_NAME}
ENV NEXT_PUBLIC_DESCRIPTION=${NEXT_PUBLIC_DESCRIPTION}
ENV NEXT_PUBLIC_LOGO_PATH=${NEXT_PUBLIC_LOGO_PATH}
ENV NEXT_PUBLIC_NEXTAUTH_URL=${NEXT_PUBLIC_NEXTAUTH_URL}
ENV NEXT_PUBLIC_API_RENIEC_DNI=${NEXT_PUBLIC_API_RENIEC_DNI}
ENV NEXT_PUBLIC_API_RENIEC_RUC=${NEXT_PUBLIC_API_RENIEC_RUC}
ENV DATABASE_URL=${DATABASE_URL}

RUN apk add --no-cache libc6-compat openssl

COPY package.json package-lock.json ./
RUN npm ci --ignore-scripts

FROM base AS builder

COPY . .
RUN npm run build

FROM node:20-alpine AS runner

WORKDIR /app
ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

COPY --from=builder /app/public ./public
COPY --from=builder /app/.next/standalone ./
COPY --from=builder /app/.next/static ./.next/static
COPY --from=builder /app/prisma ./prisma

EXPOSE 3000

CMD ["node", "server.js"]
