name: CI

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: "20.x"
  NEXT_TELEMETRY_DISABLED: "1"
  CI: "true"

jobs:
  lint_build:
    name: Lint & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Restore Next.js build cache
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: next-cache-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            next-cache-${{ runner.os }}-

      - name: Run ESLint
        run: npm run lint

      - name: Build Next.js
        run: npm run build
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          NEXT_SKIP_BUILD_STATIC_GENERATION: 'true'

      - name: Upload build artifact (.next)
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: .next
          if-no-files-found: error

  e2e_cypress:
    name: Cypress E2E
    needs: lint_build
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: next-build
          path: .next

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          install: false
          start: npm run start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 120
          command: npm run cypress:run
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          # (Opcional si usas NextAuth u otras envs en runtime)
          # NEXTAUTH_URL: http://localhost:3000
          # NEXTAUTH_SECRET: dummysecret

      - name: Save Cypress videos & screenshots (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-artifacts
          path: |
            cypress/videos
            cypress/screenshots
          if-no-files-found: ignore
